apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-stack
  namespace: kube-system
spec:
  chart: kube-prometheus-stack-46.5.0
  repo: prometheus-community/kube-prometheus-stack
  targetNamespace: monitoring
  valuesContent: |- 
    cephCommandsTimeoutSeconds: 30
    csi.enableLiveness: true
    csi.enableMetadata: true
    csi.enableOMAPGenerator: true
    csi.readAffinity.enabled: true
    csi.serviceMonitor.enabled: true
    discover.nodeAffinity: role=storage,rook; storage=ceph
    monitoring.enabled: true
